# Location of top-level MicroPython directory
MPY_DIR = ../../../SEU/micropython

# Name of module
MOD = velocidad

# Source files (.c or .py)
SRC = velocidad.c

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin)
ARCH = x86
ARCH = x64
ARCH = xtensawin

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk